### ISSUE TITLE
The Neatline admin CSS is getting randomly loaded into other admin views

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/Neatline#11]
Bizarrely, the stylesheet that makes the Omeka admin look Neatilne-y is getting randomly loaded into other views, including the main item edit view, the settings administration, and some other plugin admins. This appears to be because the conditional code that checks the current module/controller is not specific enough, and it loading the NL css when it shouldn't.

**Comment by waynegraham** [comment]
May need to pull this out and deal with the default UI from Omeka; I suspect some weird cached elements form the stylesheets.

**Comment by jeremyboggs** [comment]
> May need to pull this out and deal with the default UI from Omeka; I suspect some weird cached elements form the stylesheets.

Agreed. I think it would be better in general to rely on Omeka's default UI stuff as much as possible, especially since the UI is potentially going to change in Omeka 1.5.

**Comment by jeremyboggs** [comment]
This issue was caused by other Neatline plugins (NeatlineMaps and NeatlineTime) loading Neatline's neatline-admin.css file instead of their own. I've fixed this by changing the name of the CSS file in each of those plugins to something more unique. Those changes are already committed in the master branches of each of those plugins.

**Comment by jeremyboggs** [comment]
See the following commits for more info:
- scholarslab/NeatlineTime@f83b1e6ddbfbaf2ea985b0acb103a4449f99f9a1
- scholarslab/NeatlineMaps@3fc7cf77434a1686dc8fd3a070f3175ae2fc7cfb
