### ISSUE TITLE
Lat/Long from Omeka Geolocation plugin not imported

### ISSUE THREAD

**Issue by pleonard212** [scholarslab/Neatline#148]
Unless I'm missing something, it looks like lat/long data attached to Omeka items via the [Geolocation](http://omeka.org/codex/Plugins/Geolocation) module is invisible to NeatLine.

I understand that NeatLine wants to provide richer geospatial representations of objects, beyond the "pinpoint" -- but it would be great if Omeka users with dozens of geo-referenced objects could leverage all the labor they put into getting accurate lat/long data into the system. Perhaps objects with lat/long data could default to a simple pinpoint in NeatLine, and then let users add/modify it?

**Comment by waynegraham** [comment]
Right now the Geolocation plugin stores its latitude and longitude in a separate table (e.g. omeka_locations). Since this is only Google data, the data could be used in the spherical mercator projection. However, we need to read the terms of service a bit more closely; there is a provision that objects made using Google's geocoding service (which the Geolocation plugin does) can only be used to create Google Maps. This may actually limit the base layers that could be used in Neatline.

In the mean time, have you checked out the NeatlineFeatures plugin? It allows you to drop points and polygons on items (in the DC.coverage field).

**Comment by davidmcclure** [comment]
Peter, it's also worth mentioning that Neatline will automatically read WKT data (http://en.wikipedia.org/wiki/Well-known_text) in an item's Coverage field and immediately apply it on a Neatline exhibit.

So, if you have an item, and you put "POINT(-13630092.147686 4545224.2138399)" in the Coverage field and then bring the item into a Neatline exhibit, the point will be automatically plotted when you activate the item on the map.

And as Wayne said, Neatline seamlessly ingests any coverage data added to an item by way of the Neatline Features plugin.

**Comment by tamielbr** [comment]
I have just tried this in Omeka (2.0.2) and it did not work. I added an item an included WKY data in the Coverage field (see image). I tried with and without quotes. When I import the item into Neatline the "Geometry (Well-Known Text) " field is empty. The item does import correctly though.
![wkt data](https://f.cloud.github.com/assets/3904166/1291385/c534aa46-3041-11e3-911d-c3b3a7319e43.png)
