### ISSUE TITLE
Thumbnail of visual objects in NeatLine

### ISSUE THREAD

**Issue by pleonard212** [scholarslab/Neatline#149]
I would guess that many objects in Omeka have some kind of visual representation -- the notion of an object thumbnail is pretty well integrated into theming, etc. But the default info ingested into Neatline is only the text description, so both map pop-ups and left-column representations of objects are pretty bare.

As far as I can tell, the only way to get a visual thumbnail of an object is to switch to the "Use default item metadata" option. But the invokes a whole lot of data most people wouldn't want.  

My workflow so far is to go into Default Item mode, copy the image, then switch back to custom and paste it. Is there a better way?  

I suppose this issue also applies to "open item home page in new tab" feature, which isn't there unless you use the Default Item Metadata option.

**Comment by davidmcclure** [comment]
Yeah, right now you can get just a little bit of the DC record (the title and description) or _all_ of it. One possible solution I've thought about for this problem is to add a sort of "DC a la carte" widget, maybe a little dropdown right above the description field, where you could get a list of all the DC fields (plus any item type metadata fields) for the background Omeka item and paste the content into the description field just by clicking on the name of the element. 

That way you could stack up any arbitrary combination of elements, or just pull in the content as a starting point for editing. The dropdown could also list out the names of all the files attachments on the item, making it possible to add images without the labor intensive copy-and-paste.

**Comment by pleonard212** [comment]
Add my vote for that widget! My guess is that a pretty common use-case for NeatLine will be geo-referenced images (historic postcards, photos, etc.) A pretty big population of users will be expecting a "Flickr Map" experience -- even thought NeatLine can of course do so much more.  So a widget that lets people build that (perhaps with the inheritability of the Parent Items functionality) would go a long way towards making NeatLine work wonderfully for photos.

(I'm guessing that adjusting the specific DC records that my theme invokes on Item View will have no effect on NeatLine's ingestion of those fields...)

**Comment by davidmcclure** [comment]
This issue is addressed in the new version of Neatline with a system that makes it possible to exercise really specific control over how Omeka items are displayed in Neatline exhibits at the level of the theme.

Themes can define an `neatline/item.php` template as the default view, and then override the default with custom templates for specific exhibits and record tags. Eg,
- `item-[exhibit slug].php` matches records in the exhibit with a given slug;
- `item-[exhibit slug]-[tag]` matches records in a given exhibit with a given slug.

And so on and so forth.
