### ISSUE TITLE
After edit, Description field reverts to "Use default item metadata"

### ISSUE THREAD

**Issue by pleonard212** [scholarslab/Neatline#152]
After changing text in the Description field (in either HTML or visual mode) my objects then dim out the field and automatically check the "Use default item metadata" box.  This doesn't seem to actually be true -- if you reload the page, it resets to what it should be. Possibly related: error message "Zq[H] is undefined" popping up in the JS console from main.js:62...

**Comment by davidmcclure** [comment]
Fixed by 8acc5a527ad5caafc70e09a696deabf5790caf8e (pushed on the dev branch). This was caused by a typecasting error that was causing strings "0" and "1" to get saved to the use_dc_metadata database column, which were then getting evaluated as boolean true, regardless of the value, when parsed by the front-end code.
