### ISSUE TITLE
Non-public items

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/Neatline#177]
Items that are not flagged "public" can be added to a Neatline exhibit. When an unauthenticated user views the exhibit, they will see an alert box alerting them to a JSON error, e.g.

```
Failed to load JSON data from http://example.com/neatline-exhibits/simile/1
```

This is a little complicated because we need to allow Neatline exhibitors to develop content in "private," but know when they make an exhibit public, that there are non-public items associated with it.

**Comment by davidmcclure** [comment]
Yeah, this is tricky because it hits up against pretty basic ACL stuff in Omeka. One solution would be to add a validation process when the exhibit is set to public - check to see if there are active records in the exhibit backed by non-public Omeka items, and if so prevent the exhibit from being exposed publicly on the site.

This is sort of a big problem, though, because it can totally break an exhibit in a way that's occult to the administrator, who will always see a working exhibit unless she thinks to log out and hit the site anonymously.

**Comment by davidmcclure** [comment]
The new item-import flow in 1.2 eliminates this problem.
