### ISSUE TITLE
neatline features should use at least kml namespace 2.2

### ISSUE THREAD

**Issue by sarahgoetz** [scholarslab/Neatline#183]
Neatline Features currently uses the kml namespace 2.0., which means that it only accepts out-dated coordinate-types, i.e.: 1322001.516341,5382861.1213894, vs the kml 2.2 schema which requires a three number coordinate set, i.e 146.820,12.222, 0. 
It would be lovely to be able to paste the kml output of Google Earth into the "spatial" tab of Neatline Editor.

**Comment by waynegraham** [comment]
I assume you're suggesting that both NeatlineFeatures and Neatline serialize shapes to the KML 2.2 spec. Right now because of how OpenLayers renders polygons, the altitude for the 3D geometries doesn't really come in to play. It would be nice, though, as OpenLayers starts rolling out the new WebGL viewer to have this in place in case we get to the point where we can overlay complex 3D geometries. 

I _believe_ this should pretty pretty straight forward by passing in the `kmlns` to the map object constructor (it defaults to 2.0). 

We have had some preliminary discussions about a KML exporter, and right now it's on the list for the 2.0 version of the plugin... 

Mind submitting the KML 2.2 namespace request on the NeatlineFeatures repo too? https://github.com/scholarslab/NeatlineFeatures/issues/

**Comment by davidmcclure** [comment]
Closing this since the new version moves to WKT, in order to make use of the MySQL spatial extensions.
