### ISSUE TITLE
Server error when installing Neatline 2.0

### ISSUE THREAD

**Issue by jamahall** [scholarslab/Neatline#210]
Omeka no longer functional after installing Neatline 2.0. 

Chrome error: HTTP Error 500 (Internal Server Error): An unexpected condition was encountered while the server was attempting to fulfill the request.

**Comment by davidmcclure** [comment]
Hi @jamahall - What version of Omeka are you using? If you're on the 1.5.x line, you'll need to upgrade Omeka to 2.0.

**Comment by jamahall** [comment]
Omeka 2.0. 

After deleting the Neatline directory, Omeka is working again. On the plugins page, it now lists 'Neatline-develop', instead of 'Neatline', and below that, 'This is not a valid plugin.'

**Comment by davidmcclure** [comment]
Any chance you're trying to use the source code directly, instead of the packages posted on the blog - http://www.scholarslab.org/geospatial-and-temporal/announcing-neatline-2-0-alpha1/?

If so, you'll need to build the build the application before using it. With node/npm installed, run `npm install` and then `grunt build`.

That said, I'd recommend just using the built packages.

**Comment by jamahall** [comment]
I used the code from GitHub. Thanks for the link, it's working now!

**Comment by davidmcclure** [comment]
Hi James - Great! Sorry for the inconvenience, this really should be documented. We're working on that.
