### ISSUE TITLE
Unexpected Item Import Behavior

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/Neatline#251]
If an item is imported from an Omeka item the use cannot update the `title` and `body` cannot be updated by the user for additional context. It appears as though the item import is being run on the record PATCH.

**Comment by davidmcclure** [comment]
Yeah, this is actually deliberate, although we could do a better job at the UI level of making it clear how this works. As it is now, item-backed records in Neatline 2.x exhibits aren't allowed to diverge from the items they represent - when a record is saved, the `title` and `body` fields are "compiled" with the generated output from the source item (the DC Title field for `title`, and the entire metadata output for `body`, as defined by a theme-able `item.php` template). This is a walk-back from the way it worked in 1.x, where you could actually edit the title and body fields that were brought in from the Omeka item.

This change is debatable - it gets at the whole troublesome question of how map-entities should(n't?) map onto archival objects. The goal here was to make the relationship between items and records conceptually simpler, since users were often confused by the way it worked in 1.x - a record is either a standalone unit of content in an exhibit, or it represents an item in the Omeka collection. This eliminates the third category, the record as a context-specific _version_ of an Omeka item - a concept that's indeed very useful in some cases.

Here's a potential solution - what if we were to add `omeka_title` and `omeka_body` fields to the record model. Then, when an item-backed record is saved, we compile the `omeka_` prefixed fields, but leave the regular `title` and `body` fields as-is, open for modification in the exhibit. Then, in the public exhibit, we show the Neatline-specific content first (if it exists), and then print out the regular Omeka metadata output below the exhibit-specific content?

**Comment by jeremyboggs** [comment]
Issue has been [brought up in the Omeka forums](http://omeka.org/forums/topic/neatline-unable-to-save-record-text-changes#post-92659).

**Comment by davidmcclure** [comment]
Fixed in 2.2.
