### ISSUE TITLE
problem to see waypoints data with a not logged user

### ISSUE THREAD

**Issue by gabrielfedel** [scholarslab/Neatline#285]
When i'm not logged on omeka, if a try to see waypoints information, i can't, and after first onmove, the waypoints stop to work.

I debug a bit, and find that he try to GET this address:
/omeka/neatline/items/45?record=173 
(for record 173)

and if i'm logged, this work, and if i'm not logged this doesn't work,

**Comment by davidmcclure** [comment]
Hey Gabriel - thanks so much for bringing this to our attention! The problem here is that I forgot to register Neatline's new `/items` route as a publicly-accessible resource in the ACL. I just published a point release that fixes this - http://omeka.org/add-ons/plugins/Neatline/.

Let me know if anything else comes up!

**Comment by gabrielfedel** [comment]
Hi David! 
Thank you very much!

This thing saved us! We will launch a culture map (with omeka and neatline) today, and this problem was disturbin a lot!

a tryied to fix the ACL (before you answer), but i write some thing wrong

but now, everything is ok!

=)
