### ISSUE TITLE
Record Zoom Doesn't Respect `map_zoom`

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/Neatline#301]
If the **Default Zoom** is set without the **Default Focus** the view pane zooms to a level deeper than what is set in the `map_zoom` field. 

I suspect this is an issue in OpenLayers creating the default view of the selected item, but we need a way to deal with this.

**Comment by davidmcclure** [comment]
Actually, this is [our code](https://github.com/scholarslab/Neatline/blob/f0cb09b4d2caeabcdfb766aeb1bab6b857744070/views/shared/javascripts/src/map/map.view.js#L353) - we only apply the focus when both a focus and zoom are provided. We'd just need to check/set each individually.

**Comment by waynegraham** [comment]
Temporary fix:

``` sql
UPDATE omeka_neatline_records
SET map_focus = concat(X(coverage), ', ', Y(coverage))
, map_zoom = [zoom]
WHERE exhibit_id = [exhibit_id];
```

**Comment by davidmcclure** [comment]
This is fixed by a round of changes to the way we manifest custom focuses/zooms in 2.3. Now, a default zoom will be applied [regardless of whether a default focus is set](https://github.com/scholarslab/Neatline/blob/bug/png8/views/shared/javascripts/src/map/map.view.js#L379-399). This is handy in cases where you have a bunch of records in different locations, but you want to standardize the zoom level for all of them.
