### ISSUE TITLE
Timeline Points change color

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/Neatline#309]
This was reported via the Neatline mailing list.

There is a staring thing that happens when you scroll the timeline. If you have points of different colors, then scroll some number of years (20 was quoted, though I've sometimes found it needs to be more), the points change their color to gray when they're redrawn on the screen.

**Comment by davidmcclure** [comment]
Hmm, I suspect the [`setEventColors`](https://github.com/scholarslab/nl-widget-Simile/blob/master/views/shared/javascripts/public/simile.view.js#L260-266) method on the Backbone wrapper view in the SIMILE widget. This just gets called once when the data is initially loaded. I wonder if SIMILE has some kind of performance optimization that causes only a subset of events to get rendered when the date range is really large, or something to that effect. This might mean that only a subset of the events "exist" when that method gets called, meaning that not all of the events would get styled correctly.

**Comment by davidmcclure** [comment]
This is fixed by [73a975](https://github.com/scholarslab/nl-widget-Simile/commit/73a9756e68962c0df25cc9908cfde65ac4dfa976) on NeatlineSimile. Basically, Simile only renders the subset of events that fall within the current viewport at any given point. Before, NeatlineSimile was applying the point colors when the events were added to the timeline, but not after that. That means that very "distant" events, which weren't rendered on the initial pass after the data was ingested, weren't getting styled.

I fixed this by adding a 500-ms debounced call to the `setEventColors` method that gets called every time the band is scrolled. So, if the timeline is zoomed to a different location, there will be a half-second blip, and then the colors will get rendered appropriately on the points/spans. (Unfortunately, SIMILE doesn't provide any kind of "scroll end" event, which would make the debounce unnecessary.)
