### ISSUE TITLE
Cluttered Timeline on Neatline Eshibit 

### ISSUE THREAD

**Issue by mcarring** [scholarslab/Neatline#317]
Hello, 

I have many events on the same timeline and some are located at the bottom of the timeline which gives a very cluttered appearance. I've outlined the problem with the red rectangle. Any ideas on where I could change the CSS to adjust the height or spacing?
![timelineclutter](https://cloud.githubusercontent.com/assets/7989213/3463047/0f3e2fc0-0235-11e4-9fd2-95a443f77a1a.png)

**Comment by waynegraham** [comment]
@clioweb You've spent more time with SIMILE Timeline than me, is `label` style-able? From what I see here it looks like that title is longer than the interval so Simile is forcing the objects down.

**Comment by jeremyboggs** [comment]
@waynegraham Yup, it's wrapped with a `div` with a class attribute "timeline-event-label". Each one also has a unique value for the ID attribute, which can be exposed using web developer tools. As for how to actually address the issue the OP brings up, I'm not sure offhand. Suspect having a fixed width for labels would cause similar problems, because you'd be forcing multiple lines.

An alternative to styling the label itself would be to increase the height of the timeline overall. The bands have a percentage height, which is further constrained by total height of the `#simile` container. See the "stylus" file at https://github.com/scholarslab/nl-widget-Simile/blob/master/views/shared/css/stylus/public/simile.styl#L65. The entire timeline is set to 20% height. I suppose this could all be overridden in the theme's CSS, something like:

``` css
#simile {
    height: 30% !important; /* Clobbers values from any other declarations with !important, regardless of cascade. */
}
```

**Comment by mcarring** [comment]
Wayne, 
I used the 
#simile {
    height: 30% !important; /\* Clobbers values from any other declarations with !important, regardless of cascade. */
}

It worked and the events on the timeline have moved upwards.

**Comment by mcarring** [comment]
I had to use 40% and may have to adjust this more depending on the data. 
![finalevents](https://cloud.githubusercontent.com/assets/7989213/3501083/4cb5ef1a-0612-11e4-8e39-e3d09cd1a9c0.png)

**Comment by waynegraham** [comment]
Looks like this technique has fixed the issue...
