### ISSUE TITLE
Timeline and Scrolling in Browser

### ISSUE THREAD

**Issue by mcarring** [scholarslab/Neatline#324]
We have numerous events in our timeline so that users need to scroll down in a browser to see the years. We would like to have the timeline exhibit more user friendly by moving the years to the top of the browser. Is there any way to do this with the Simile CSS? 

![timelineinbrowser](https://cloud.githubusercontent.com/assets/7989213/3756731/3df5fa84-1831-11e4-84ae-ad2ad9c4d612.png)

**Comment by davidmcclure** [comment]
Hey @mcarring,

Sorry for the slow response to this. Unfortunately, I don't believe that there's a way to change this in Simile. Really, the bigger problem is that Simile doesn't have a good UI strategy to handle the highly "stacked" events that you've got there - where lots of events are clustered around the same date, which pins them all to the same X-axis position and forces them on top of each other.

On that note, though, I'm actually working on a project right now that involves integrating Neatline with the [Vis.js timeline](http://visjs.org/#timeline), which handles this situation really nicely (the height of the timeline grows and shrinks depending on the height of the event stack). I'm going to pull this out this work and release it as a separate sub-plugin for Neatline in the next couple weeks, so that might be a good solution.

Best,
David
