### ISSUE TITLE
"Fill Opacity (Selected)" not working  

### ISSUE THREAD

**Issue by csbailey5t** [scholarslab/Neatline#331]
With Omeka 2.2.2 and Neatline 2.3.0, "Fill Opacity (Selected)" in the Neatline Styles tab is not working. It has no effect on the opacity of the record when the record is selected. The regular "Fill Opacity" is still working.

**Comment by davidmcclure** [comment]
Hey @csbailey5t - Hmm, I can't replicate that, seems OK over here. The "selected" style is actually rendered when the cursor hovers on a shape, and when the shape is selected. So, if you have a polygon, and **Fill Opacity** is 0.1, and **Fill Opacity (Selected)** is 1.0, it should go from very translucent to fully opaque when the cursor hovers, and then stay opaque after it's clicked. Is it just staying at 0.1 opacity, even when the cursor hovers/clicks?

**Comment by csbailey5t** [comment]
Issue resolved. Fill Opacity (Selected) is working. The issue was specific to WMS layers on a record, but the Opacity does not affect the WMS layer. We may want to consider adding the ability to change the opacity of a WMS layer as a feature.

**Comment by hannahlj007** [comment]
Hi,

I'm working on a project that involves multiple WMS layers in over one location that need to be viewed individually. While I've used Before/After to make this happen to a certain extent, when you view the top most layer bits of the other layers stick out around it because they're not all the same size. It would be great if Fill Opacity (Selected) worked for WMS layers.
