### ISSUE TITLE
Documentation Corrections

### ISSUE THREAD

**Issue by trevorberman** [scholarslab/Neatline#337]
I was reading through the documentation while troubleshooting another issue and found these sections of text that need correction.

http://docs.neatline.org/upgrading-to-v2.html
A new programming API and “sub-plugin”... <-- the closing quote is styled funky/faded-out (Chrome and Firefox).

http://docs.neatline.org/creating-exhibits.html
...placed to the ~~site~~ side of the exhibit and given more room...
AND
...integrates tightly with the ~~NeatlineNarrative~~ NeatlineText widget

http://docs.neatline.org/text-tab.html
Specifically, the ~~Neatline~~ ~~Narrative~~ NeatlineText plugin...

**Comment by waynegraham** [comment]
Tranks @trevorberman! Since I know you know how to use git, mind sending these updates as a pull-request?

If you go to https://github.com/scholarslab/Neatline/tree/gh-pages and navigate to one of the pages (e.g. https://github.com/scholarslab/Neatline/blob/gh-pages/text-tab.md). If you click on the pencil icon (or hit the 'e' character), you can change the text. This way you'll get contribution credit in the commit history and show up on the graphs :)

**Comment by trevorberman** [comment]
#2 and #3, done and done Wayne!

However, didn't address 1st on list. Double-quotes look correct in the markdown. Something funky going on in the styling of the trailing one though. Only looked correct if I replaced it with straight quotes using dev-tools + unable to directly get at the CSS (looks like it's coming straight off Neatline.org).

**Comment by waynegraham** [comment]
I think that needs to be just straight up quotes; note right and left angle quotes. I think that might be left over from composing in Word or something...

**Comment by waynegraham** [comment]
@trevorberman Thanks for doing this!
