### ISSUE TITLE
Refactor part of this into NeatlineFeatures

### ISSUE THREAD

**Issue by erochest** [scholarslab/Neatline#35]
The features to draw on the maps and save the information needs to be pulled into a separate Omeka plugin that can be installed separately.

**Comment by davidmcclure** [comment]
The features plugin should:
- Add a stripped-down NL editing interface directly onto the item edit forms that just includes the OpenLayers map instantiation and drawing features (the neatline_map.js widget, essentially).
- Right now, the targets for the ajax calls that commit saves in the NL editor live in the item editor widget. Since this will not be present in a map-only instantiation, these requests need to be constructed and implemented in the features-specific instantiation. Probably the cleanest way to do this is to create an object literal that sits outside of the widget with a series of functions that, when called, return a prepared ajax request for some or another task (save, get features, etc.). This is the direction that I am taking the main NL plugin.
- The features plugin should save the feature vector data directly into the DC Coverage Store field. Since this is what the NL plugin currently does, the code to do this is extant in NL as of 8814d53a358d563e719e08e10475dd7d7428435f, though this will change after the new NL model schema is implemented.
- The plugin needs to make it possible to choose and then toggle among different possible "base layer" cases for the annotations. If there are images uploaded on the item, it should be possible to use any of the images as the base layer. Alternatively, it should be possible to use a generic geographic base layer (open street map, etc.), which would be pulled in via WMS. This will require some UX addition that is specific to the features plugin - some kind of tray to choose the background.

This is a non-trivial chunk of development.

**Comment by davidmcclure** [comment]
Done.
